import {
  Box,
  Flex,
  Grid,
  GridItem,
  Input,
  Text,
  Center,
  useDisclosure,
} from "@chakra-ui/react";
import { useEffect, useRef, useState } from "react";
import { AiOutlineConsoleSql, AiOutlineStar } from "react-icons/ai";
import { BsFilterCircleFill } from "react-icons/bs";
import { useSearchParams } from "react-router-dom";
import { useParams } from "react-router-dom";
import SingleImage from "./SingleImage";
import "./style.css";

const Home = () => {
  const [allImages, setAllImages] = useState([]);
  const [searchParmas, setSearchParams] = useSearchParams();
  var id = useRef(null);

  const getData = () => {
    fetch("https://kinesis-server.vercel.app/post")
      .then((res) => res.json())
      .then(({ data }) => setAllImages(data))
      .catch((err) => console.log(err));
  };

  useEffect(() => {
    getData();
  }, []);

  const debounceSearch = async (e) => {
    try {
      if (e.target.value === "") {
        getData();
      } else {
        setSearchParams({ q: e.target.value });
        if (id.current) {
          clearTimeout(id.current);
        }
        id.current = setTimeout(async () => {
          const jsonData = await fetch(
            `https://kinesis-server.vercel.app/search?q=${e.target.value}`
          );
          const { data } = await jsonData.json();
          setAllImages(data);
        }, 1000);
      }
    } catch (error) {
      console.log(error.message);
    }
  };

  return (
    <Box>
      <Flex
        justify={"space-between"}
        px={"20px"}
        w={{ lg: "80%" }}
        align={"center"}
        m={"auto"}
        pt={"85px"}
      >
        <Box>
          <Text fontWeight={"bold"} fontSize={{ base: "18px", sm: "24px" }}>
            Community Showcase
          </Text>
        </Box>
        <Flex align={"center"} gap={3}>
          <Flex align={"center"} gap={1}>
            <BsFilterCircleFill color="red" />
            <Text fontWeight={"bold"} onClick={getData}>
              Recent
            </Text>
          </Flex>
          <Flex align={"center"}>
            {/* <AiOutlineStar />
            <Text fontWeight={"bold"}>Top</Text> */}
          </Flex>
        </Flex>
      </Flex>
      <Box w={{ lg: "80%" }} m={"auto"} p={4}>
        <Input
          type="text"
          placeholder="Search for images"
          onChange={(e) => debounceSearch(e)}
        />
      </Box>
      <Center w={{ lg: "80%" }} m={"auto"} p={4}>
        <Text fontSize={{ base: "14px", md: "16px" }}>
          Browser through a collection of imaginative and visually stunning
          images generated by Kinesis.AI community
        </Text>
      </Center>
      <Grid
        templateColumns="repeat(4, 1fr)"
        templateRows="repeat(3, 1fr)"
        gap={3}
        p={{ base: 2, md: 4 }}
        w={{ lg: "80%" }}
        m={"auto"}
      >
        {allImages?.map((image, i) => {
          return (
            <GridItem
              rowSpan={{ base: 4, sm: 1, lg: i % 3 === 0 ? 2 : 1 }}
              key={i}
              colSpan={{ base: 4, sm: 2, lg: i % 3 === 0 ? 2 : 1 }}
            >
              <SingleImage image={image} />
            </GridItem>
          );
        })}
      </Grid>
    </Box>
  );
};

export default Home;
